[general]
library_name = "libcsfml"
library_names = {"Audio/.*.h" = "libcsfml_audio", "Graphics/.*.h" = "libcsfml_graphics", "Network/.*.h" = "libcsfml_network", "System/.*.h" = "libcsfml_system", "Window/.*.h" = "libcsfml_window"}
output_file_path = "../src/LibCSFML.jl"
module_name = "LibCSFML"
jll_pkg_name = "CSFML_jll"
export_symbol_prefixes = ["sf"]
use_deterministic_symbol = true

printer_blacklist = [
    "CSFML_SYSTEM_API",
    "CSFML_AUDIO_API",
    "CSFML_WINDOW_API",
    "CSFML_GRAPHICS_API",
    "CSFML_NETWORK_API",
]

[codegen.macro]
macro_mode = "basic"